name: Rflink Build Tests

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio==6.1.5
        pio update
        pip install esptool

    - name: Make a BUILDNAME
      run: echo "RFLINK_BUILDNAME=\"$(date '+%Y%m%d-%H%M%S')-${GITHUB_REF#refs/heads/}\"" >> $GITHUB_ENV

    - name: ESP32_none_enabled
      run: |
        echo "buid name $RFLINK_BUILDNAME"
        pio run --project-conf .travis.platformio.ini --environment ESP32_none_enabled

    - name: ESP32_sw
      run: |
        pio run --project-conf .travis.platformio.ini --environment ESP32_sw

