name: Rflink Build Tests

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U platformio
        pio update
        pip install esptool

    - name: Make a BUILDNAME
      run: echo "RFLINK_BUILDNAME=\"$(date '+%Y%m%d-%H%M%S')-${GITHUB_REF#refs/heads/}\"" >> $GITHUB_ENV

    - name: ESP32_none_enabled
      run: |
        echo "buid name $RFLINK_BUILDNAME"
        pio run --project-conf .travis.platformio.ini --environment ESP32_none_enabled
    - name: ESP32_sw
      run: |
        pio run --project-conf .travis.platformio.ini --environment ESP32_sw


    - name: D1_none_enabled
      run: |
        pio run --project-conf .travis.platformio.ini --environment D1_none_enabled
    - name: D1_sw
      run: |
        pio run --project-conf .travis.platformio.ini --environment D1_sw

    - name: Copy firmwares in 1 place
      if: github.event_name == 'push'
      run: |
        mkdir firmwares
        cp .pio/build/ESP32_sw/firmware.bin firmwares/esp32-firmware-OTA.bin
        cp .pio/build/ESP32_sw/partitions.bin firmwares/esp32-partitions.bin
        cp .pio/build/D1_sw/firmware.bin firmwares/esp8266-firmware.bin
        cd firmwares
        cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/partitions/boot_app0.bin .
        cp /home/runner/.platformio/packages/framework-arduinoespressif32/tools/sdk/bin/bootloader_dio_40m.bin .
        python ../tools/esp32-makeimg.py bootloader_dio_40m.bin esp32-partitions.bin boot_app0.bin esp32-firmware-OTA.bin esp32-full.img
        cd ..

    - name: Publish firmware for Master branch
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Development Build"
        files: |
          firmwares/*

    - name: Publish firmware for RadioLib branch
      if: github.ref == 'refs/heads/RadioLib' && github.event_name == 'push'
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly-RadioLib"
        prerelease: true
        title: "Development Build"
        files: |
          firmwares/*



